package cn.xdl.ovls.entity;

public class Knowledge {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.Id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.name
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.subject_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    private Integer subjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column knowledge.chapter_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    private Integer chapterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.Id
     *
     * @return the value of knowledge.Id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.Id
     *
     * @param id the value for knowledge.Id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.name
     *
     * @return the value of knowledge.name
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.name
     *
     * @param name the value for knowledge.name
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.subject_id
     *
     * @return the value of knowledge.subject_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public Integer getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.subject_id
     *
     * @param subjectId the value for knowledge.subject_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public void setSubjectId(Integer subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column knowledge.chapter_id
     *
     * @return the value of knowledge.chapter_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public Integer getChapterId() {
        return chapterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column knowledge.chapter_id
     *
     * @param chapterId the value for knowledge.chapter_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public void setChapterId(Integer chapterId) {
        this.chapterId = chapterId;
    }
}