package cn.xdl.ovls.entity;

public class QuestionOptions {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_options.option_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    private Integer optionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_options.question_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    private Integer questionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_options.option_name
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    private String optionName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.option_id
     *
     * @return the value of question_options.option_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public Integer getOptionId() {
        return optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.option_id
     *
     * @param optionId the value for question_options.option_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public void setOptionId(Integer optionId) {
        this.optionId = optionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.question_id
     *
     * @return the value of question_options.question_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public Integer getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.question_id
     *
     * @param questionId the value for question_options.question_id
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public void setQuestionId(Integer questionId) {
        this.questionId = questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_options.option_name
     *
     * @return the value of question_options.option_name
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_options.option_name
     *
     * @param optionName the value for question_options.option_name
     *
     * @mbg.generated Wed Jun 05 10:30:51 CST 2019
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }
}